This is an internal working file generated by the Source Browser.
16:06 58s
D:\proj\TC007_OBD_STM32_MB\bootloader\bootloader_src\download.c
D:\proj\TC007_OBD_STM32_MB\bootloader\bootloader_src\download.c
-D
VECT_TAB_FLASH
-D
IAR_ARM_CM3
-lcN
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\Debug\List\
-o
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\Debug\Obj\
--no_cse
--no_unroll
--no_inline
--no_code_motion
--no_tbaa
--no_clustering
--no_scheduling
--debug
--endian=little
--cpu=Cortex-M3
-e
--fpu=None
--dlib_config
D:\Program Files\IAR Systems\Embedded Workbench 6.0_3\arm\INC\c\DLib_Config_Full.h
-I
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\.\
-I
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\..\bootloader_src\
-I
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\..\bootloader_src\library\
-I
D:\proj\TC007_OBD_STM32_MB\bootloader\IAR_STM32_BOOT\..\bootloader_src\library\inc\
-Ol
--use_c++_inline
--require_prototypes
